dist: xenial
language: python
matrix:
    include:
        -   env: TOXENV=py27
        -   env: TOXENV=py36
            python: 3.6
        -   env: TOXENV=pypy
            python: pypy2.7-5.10.0
        -   env: TOXENV=py38
            python: 3.8-dev
install: pip install coveralls tox
script: tox
after_success: coveralls
cache:
    directories:
        - $HOME/.cache/pip
        - $HOME/.cache/pre-commit
