trigger:
  branches:
    include: [master, test-me-*]

resources:
  repositories:
    - repository: asottile
      type: github
      endpoint: asottile-github
      name: asottile/azure-pipeline-templates
      ref: refs/tags/v0.0.4

jobs:
- template: job--python-tox.yml@asottile
  parameters:
    toxenvs: [py27, py37]
    os: windows
- template: job--python-tox.yml@asottile
  parameters:
    toxenvs: [pypy, pypy3, py27, py36, py37, py38]
    os: linux
